package com.vaadinDemo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.VaadinRequest;
import com.vaadin.ui.*;

public class DetailForm extends UI {





    
    @Override
    protected void init(VaadinRequest vaadinRequest) {

    }

    public void init() {
        final Label title = new Label ("Enter your Company Details");
        final VerticalLayout layout = new VerticalLayout();
        final TextField emails= new TextField();
        final TextField name = new TextField();


        name.setCaption("Enter your Username");
        emails.setCaption("Enter your Company Email");

        layout.addComponent(name);
    }
}
